sudo: required
dist: trusty
language: rust
cache: cargo

os:
    - linux
    - osx
    - windows
    
rust:
  - stable
  - beta
  - nightly
   # Minimum suported version
  - 1.31.1
  
matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

addons:
    apt:
        packages:
            - libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi
  
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable && "TRAVIS_OS_NAME" == linux]]; then
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
