os:
    - linux
    - osx
    - windows

sudo: false
language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly
   # Minimum suported version
  - 1.31.1

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

